version: "3.8"

services:
    mongo-db:
        image: mongo:latest
        container_name: mongo-db
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo_user
            MONGO_INITDB_ROOT_PASSWORD: mongo_password
            MONGO_INITDB_DATABASE: investments_db
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
